import {
  User,
  ClassRoom,
  Team,
  TeamMemberRecord,
  Assignment,
  AssignmentProgress,
  TeamActivity,
  Quiz,
  QuizQuestion,
  ReflectionTemplate,
  FormalTest,
  TestQuestion,
  AppSettings,
  AuditLog,
} from "../src/types/index.ts";

export const INITIAL_USERS: User[] = [
  {
    id: "admin",
    name: "Administrator",
    username: "admin",
    password: "admin123",
    role: "ADMIN",
    classId: "class-8a",
    status: "ACTIVE",
    avatar: "🛡️",
    createdAt: new Date(Date.now() - 86400000 * 30).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 30).toISOString(),
  },
  {
    id: "teacher01",
    name: "Pak Hendra, S.Kom",
    username: "teacher01",
    password: "guru123",
    role: "TEACHER",
    classId: "class-8a",
    status: "ACTIVE",
    avatar: "👨‍🏫",
    createdAt: new Date(Date.now() - 86400000 * 20).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 20).toISOString(),
  },
  {
    id: "student01",
    name: "Rizki",
    username: "student01",
    password: "siswa123",
    role: "TEAM_LEADER",
    classId: "class-8a",
    teamId: "team-1",
    status: "ACTIVE",
    avatar: "👨‍💻",
    createdAt: new Date(Date.now() - 86400000 * 10).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 10).toISOString(),
  },
  {
    id: "student02",
    name: "Andi",
    username: "student02",
    password: "siswa123",
    role: "STUDENT",
    classId: "class-8a",
    teamId: "team-1",
    status: "ACTIVE",
    avatar: "🧑‍🎓",
    createdAt: new Date(Date.now() - 86400000 * 10).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 10).toISOString(),
  },
  {
    id: "student03",
    name: "Budi",
    username: "student03",
    password: "siswa123",
    role: "STUDENT",
    classId: "class-8a",
    teamId: "team-1",
    status: "ACTIVE",
    avatar: "🧑‍💻",
    createdAt: new Date(Date.now() - 86400000 * 10).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 10).toISOString(),
  },
  {
    id: "student04",
    name: "Sinta",
    username: "student04",
    password: "siswa123",
    role: "STUDENT",
    classId: "class-8a",
    teamId: "team-1",
    status: "ACTIVE",
    avatar: "👩‍🎓",
    createdAt: new Date(Date.now() - 86400000 * 10).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 10).toISOString(),
  },
  {
    id: "student05",
    name: "Dimas",
    username: "student05",
    password: "siswa123",
    role: "STUDENT",
    classId: "class-8a",
    teamId: "team-1",
    status: "ACTIVE",
    avatar: "🧑‍🎨",
    createdAt: new Date(Date.now() - 86400000 * 10).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 10).toISOString(),
  },
  {
    id: "student06",
    name: "Alya",
    username: "student06",
    password: "siswa123",
    role: "TEAM_LEADER",
    classId: "class-8a",
    teamId: "team-2",
    status: "ACTIVE",
    avatar: "👩‍🔬",
    createdAt: new Date(Date.now() - 86400000 * 10).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 10).toISOString(),
  },
];

export const INITIAL_CLASSES: ClassRoom[] = [
  {
    id: "class-8a",
    name: "VIII A",
    description: "Kelas Unggulan Algoritma & Dasar Pemrograman C",
    academicYear: "2026/2027",
    createdAt: new Date(Date.now() - 86400000 * 30).toISOString(),
  },
  {
    id: "class-8b",
    name: "VIII B",
    description: "Kelas Terapan Logika Komputasi",
    academicYear: "2026/2027",
    createdAt: new Date(Date.now() - 86400000 * 30).toISOString(),
  },
  {
    id: "class-8c",
    name: "VIII C",
    description: "Kelas Eksperimen Pemecahan Masalah Komputer",
    academicYear: "2026/2027",
    createdAt: new Date(Date.now() - 86400000 * 30).toISOString(),
  },
];

export const INITIAL_TEAMS: Team[] = [
  {
    id: "team-1",
    teamName: "LOOP MASTER",
    teamCode: "LP-4821",
    classId: "class-8a",
    leaderId: "student01", // Rizki
    createdBy: "student01",
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    status: "ACTIVE",
  },
  {
    id: "team-2",
    teamName: "CODE RUNNER",
    teamCode: "CR-3912",
    classId: "class-8a",
    leaderId: "student06", // Alya
    createdBy: "student06",
    createdAt: new Date(Date.now() - 86400000 * 4).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 4).toISOString(),
    status: "ACTIVE",
  },
  {
    id: "team-3",
    teamName: "FORCE LOOP",
    teamCode: "FL-8104",
    classId: "class-8b",
    leaderId: "student05",
    createdBy: "student05",
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    status: "ACTIVE",
  },
];

export const INITIAL_TEAM_MEMBERS: TeamMemberRecord[] = [
  {
    id: "tm-1",
    teamId: "team-1",
    userId: "student01",
    role: "LEADER",
    joinedAt: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
  {
    id: "tm-2",
    teamId: "team-1",
    userId: "student02",
    role: "MEMBER",
    joinedAt: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
  {
    id: "tm-3",
    teamId: "team-1",
    userId: "student03",
    role: "MEMBER",
    joinedAt: new Date(Date.now() - 86400000 * 4).toISOString(),
  },
  {
    id: "tm-4",
    teamId: "team-1",
    userId: "student04",
    role: "MEMBER",
    joinedAt: new Date(Date.now() - 86400000 * 4).toISOString(),
  },
  {
    id: "tm-5",
    teamId: "team-1",
    userId: "student05",
    role: "MEMBER",
    joinedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
];

export const INITIAL_ASSIGNMENTS: Assignment[] = [
  {
    id: "asg-1",
    title: "Loop Challenge 01",
    description: "Misi kolaborasi tim perulangan C: Tuntaskan Level 1–5, ikuti kuis konsep for & while, sampaikan refleksi kelompok, dan selesaikan tes akhir.",
    type: "MIXED",
    mode: "TEAM",
    levelIds: [1, 2, 3, 4, 5],
    quizId: "quiz-1",
    reflectionId: "ref-1",
    testId: "test-1",
    targetType: "CLASS",
    targetId: "class-8a",
    deadline: "2026-09-20T23:59:59.000Z",
    createdBy: "teacher01",
    status: "ACTIVE",
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: "asg-2",
    title: "Algoritma Mandiri: Dynamic Sentinel",
    description: "Tugas pemahaman individu untuk Level 6 menggunakan sensor jalur dan kondisi dinamis perulangan.",
    type: "GAME",
    mode: "INDIVIDUAL",
    levelIds: [6],
    targetType: "CLASS",
    targetId: "class-8a",
    deadline: "2026-09-25T23:59:59.000Z",
    createdBy: "teacher01",
    status: "ACTIVE",
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
];

export const INITIAL_ASSIGNMENT_PROGRESS: AssignmentProgress[] = [
  {
    id: "prog-team-1-asg-1",
    assignmentId: "asg-1",
    teamId: "team-1",
    status: "IN_PROGRESS",
    completedLevelIds: [1, 2, 3, 4],
    gameProgress: 80, // 4 of 5 levels completed
    quizScore: 80, // 8 / 10
    quizCompleted: true,
    reflectionSubmitted: true,
    testScore: 0,
    testCompleted: false,
    score: 86,
    startedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
];

export const INITIAL_TEAM_ACTIVITIES: TeamActivity[] = [
  {
    id: "act-1",
    teamId: "team-1",
    userId: "student01",
    userName: "Rizki",
    activityType: "CREATE_TEAM",
    metadata: { teamName: "LOOP MASTER", code: "LP-4821" },
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
  {
    id: "act-2",
    teamId: "team-1",
    userId: "student02",
    userName: "Andi",
    activityType: "JOIN_TEAM",
    metadata: { role: "MEMBER" },
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
  {
    id: "act-3",
    teamId: "team-1",
    userId: "student03",
    userName: "Budi",
    activityType: "JOIN_TEAM",
    metadata: { role: "MEMBER" },
    createdAt: new Date(Date.now() - 86400000 * 4).toISOString(),
  },
  {
    id: "act-4",
    teamId: "team-1",
    userId: "student01",
    userName: "Rizki",
    activityType: "COMPLETE_LEVEL",
    metadata: { levelId: 1, stars: 3 },
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: "act-5",
    teamId: "team-1",
    userId: "student02",
    userName: "Andi",
    activityType: "COMPLETE_LEVEL",
    metadata: { levelId: 2, stars: 3 },
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: "act-6",
    teamId: "team-1",
    userId: "student03",
    userName: "Budi",
    activityType: "COMPLETE_LEVEL",
    metadata: { levelId: 3, stars: 3 },
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: "act-7",
    teamId: "team-1",
    userId: "student04",
    userName: "Sinta",
    activityType: "COMPLETE_LEVEL",
    metadata: { levelId: 4, stars: 3 },
    createdAt: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
  {
    id: "act-8",
    teamId: "team-1",
    userId: "student01",
    userName: "Rizki",
    activityType: "SUBMIT_QUIZ",
    metadata: { score: 80, quizTitle: "Dasar Perulangan C" },
    createdAt: new Date(Date.now() - 3600000 * 12).toISOString(),
  },
  {
    id: "act-9",
    teamId: "team-1",
    userId: "student01",
    userName: "Rizki",
    activityType: "SUBMIT_REFLECTION",
    metadata: { reflectionTitle: "Refleksi Pembelajaran Perulangan & Tim" },
    createdAt: new Date(Date.now() - 3600000 * 4).toISOString(),
  },
];

export const INITIAL_QUIZZES: Quiz[] = [
  {
    id: "quiz-1",
    title: "Dasar Perulangan C",
    description: "Evaluasi pemahaman konsep perulangan for, while, do-while, batas kondisi, dan alur iterasi.",
    timeLimit: 10,
    passingScore: 70,
    createdBy: "teacher01",
    status: "ACTIVE",
    questionCount: 5,
  },
];

export const INITIAL_QUIZ_QUESTIONS: QuizQuestion[] = [
  {
    id: "qq-1",
    quizId: "quiz-1",
    question: "Perhatikan potongan kode C berikut. Berapa kali perulangan dijalankan?",
    codeSnippet: `for (int i = 0; i < 5; i++) {\n    printf("%d ", i);\n}`,
    type: "CODE_OUTPUT",
    options: ["4", "5", "6", "Infinite"],
    correctAnswer: "5",
    explanation: "Variabel i dimulai dari 0 dan berjalan selama i < 5 (yaitu i = 0, 1, 2, 3, 4), total tepat 5 kali perulangan.",
    points: 20,
    order: 1,
    conceptTag: "FOR_LOOP",
  },
  {
    id: "qq-2",
    quizId: "quiz-1",
    question: "Struktur loop apa yang paling sesuai jika jumlah pengulangan sudah diketahui secara pasti sejak awal?",
    codeSnippet: `// Contoh: mengulang tepat 10 kali`,
    type: "CHOOSE_LOOP",
    options: ["FOR", "WHILE", "DO...WHILE", "GOTO"],
    correctAnswer: "FOR",
    explanation: "Loop 'for' dirancang khusus untuk counter-controlled loop di mana nilai awal, kondisi akhir, dan perubahan nilai sudah terdefinisi.",
    points: 20,
    order: 2,
    conceptTag: "FOR_LOOP",
  },
  {
    id: "qq-3",
    quizId: "quiz-1",
    question: "Berapa banyak karakter bintang (*) yang akan tercetak pada layar?",
    codeSnippet: `int i = 1;\nwhile (i <= 3) {\n    printf("*");\n    i++;\n}`,
    type: "CODE_OUTPUT",
    options: ["2", "3", "4", "Tidak ada"],
    correctAnswer: "3",
    explanation: "Loop berjalan untuk i = 1, i = 2, dan i = 3. Saat i mencapai 4, kondisi (i <= 3) menjadi false sehingga loop berhenti.",
    points: 20,
    order: 3,
    conceptTag: "WHILE_LOOP",
  },
  {
    id: "qq-4",
    quizId: "quiz-1",
    question: "Pernyataan perulangan 'do...while' menjamin bahwa blok kode di dalamnya akan dieksekusi minimal sebanyak:",
    type: "MULTIPLE_CHOICE",
    options: ["0 kali", "1 kali", "2 kali", "Tergantung kondisi awal"],
    correctAnswer: "1 kali",
    explanation: "Pada 'do...while', kondisi dievaluasi di akhir (post-test), sehingga badan loop selalu dijalankan minimal 1 kali terlebih dahulu.",
    points: 20,
    order: 4,
    conceptTag: "DO_WHILE",
  },
  {
    id: "qq-5",
    quizId: "quiz-1",
    question: "Apa efek instruksi 'break;' ketika dipanggil di dalam suatu perulangan?",
    codeSnippet: `while (1) {\n    if (sensorDinding()) break;\n    maju();\n}`,
    type: "IDENTIFY_ERROR",
    options: [
      "Menghentikan perulangan saat itu juga dan keluar dari blok loop",
      "Melewatkan iterasi sekarang dan lanjut ke iterasi berikutnya",
      "Mengulang kembali proses loop dari iterasi pertama",
      "Menghapus nilai variabel perulangan",
    ],
    correctAnswer: "Menghentikan perulangan saat itu juga dan keluar dari blok loop",
    explanation: "Perintah 'break;' memaksa terminasi segera dari blok loop terdekat dan melanjutkan eksekusi program setelah penutup loop.",
    points: 20,
    order: 5,
    conceptTag: "CONTROL_FLOW",
  },
];

export const INITIAL_REFLECTIONS: ReflectionTemplate[] = [
  {
    id: "ref-1",
    title: "Refleksi Pembelajaran Perulangan & Kolaborasi Tim",
    assignmentId: "asg-1",
    createdBy: "teacher01",
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    questions: [
      {
        id: "rf-q1",
        question: "1. Apa yang kamu pahami tentang konsep perulangan (loop) dalam pemrograman C?",
        placeholder: "Tuliskan pemahamanmu tentang bagaimana komputer mengulang instruksi secara otomatis...",
      },
      {
        id: "rf-q2",
        question: "2. Apa bagian atau tantangan yang paling sulit saat menyusun blok loop?",
        placeholder: "Misalnya menentukan batas kondisi, menghindari tabrakan, atau off-by-one...",
      },
      {
        id: "rf-q3",
        question: "3. Menurut analisismu, apa perbedaan utama antara for loop dan while loop?",
        placeholder: "Kapan kamu memilih menggunakan for dan kapan memilih while...",
      },
      {
        id: "rf-q4",
        question: "4. Jika diberi kesempatan mengulang misi tadi, apa yang akan kamu perbaiki pada kodemu?",
        placeholder: "Tuliskan ide optimasi atau pengurangan jumlah balok yang bisa dilakukan...",
      },
      {
        id: "rf-q5",
        question: "5. Bagaimana dinamika kerja sama dan komunikasi di tim kalian?",
        placeholder: "Jelaskan bagaimana anggota tim saling membantu dalam memecahkan masalah...",
        isTeamQuestion: true,
      },
    ],
  },
];

export const INITIAL_TESTS: FormalTest[] = [
  {
    id: "test-1",
    title: "C Loop Assessment: Asesmen Kompetensi Perulangan C",
    description: "Uji kompetensi formal materi perulangan C: analisis luaran kode, pelacakan variabel (tracing), deteksi batas kondisi, dan efisiensi algoritma.",
    duration: 15, // 15 menit
    passingScore: 75,
    maxAttempts: 2,
    questionCount: 5,
    createdBy: "teacher01",
    status: "ACTIVE",
  },
];

export const INITIAL_TEST_QUESTIONS: TestQuestion[] = [
  {
    id: "tq-1",
    testId: "test-1",
    question: "Perhatikan program berikut. Nilai apa saja yang akan dicetak ke layar?",
    codeSnippet: `int i = 0;\nwhile (i < 4) {\n    printf("%d ", i);\n    i++;\n}`,
    type: "CODE_OUTPUT",
    options: ["0 1 2 3 4", "0 1 2 3", "1 2 3 4", "0 1 2"],
    points: 20,
    order: 1,
    answer: "0 1 2 3",
  },
  {
    id: "tq-2",
    testId: "test-1",
    question: "Berapa total nilai akhir variabel sum setelah loop selesai berjalan?",
    codeSnippet: `int sum = 0;\nfor (int i = 1; i <= 4; i++) {\n    sum = sum + i;\n}`,
    type: "PREDICT_ITERATIONS",
    options: ["6", "10", "15", "4"],
    points: 20,
    order: 2,
    answer: "10",
  },
  {
    id: "tq-3",
    testId: "test-1",
    question: "Apa masalah utama pada potongan kode C berikut ini?",
    codeSnippet: `int count = 1;\nwhile (count > 0) {\n    printf("Running...\\n");\n    count++;\n}`,
    type: "FIND_ERROR",
    options: [
      "Terjadi infinite loop (perulangan tak terhingga) karena nilai count selalu bertambah dan lebih dari 0",
      "Sintaks printf salah",
      "Variabel count tidak dideklarasikan",
      "Kondisi count > 0 tidak valid dalam bahasa C",
    ],
    points: 20,
    order: 3,
    answer: "Terjadi infinite loop (perulangan tak terhingga) karena nilai count selalu bertambah dan lebih dari 0",
  },
  {
    id: "tq-4",
    testId: "test-1",
    question: "Berapa kali kata 'LOOP' akan dicetak oleh struktur nested loop berikut?",
    codeSnippet: `for (int r = 0; r < 2; r++) {\n    for (int c = 0; c < 3; c++) {\n        printf("LOOP ");\n    }\n}`,
    type: "PREDICT_ITERATIONS",
    options: ["5 kali", "6 kali", "2 kali", "3 kali"],
    points: 20,
    order: 4,
    answer: "6 kali",
  },
  {
    id: "tq-5",
    testId: "test-1",
    question: "Manakah penulisan loop for yang benar untuk mencetak angka ganjil 1, 3, 5, 7, 9?",
    type: "MULTIPLE_CHOICE",
    options: [
      "for (int i = 1; i < 10; i += 2)",
      "for (int i = 1; i <= 10; i++)",
      "for (int i = 0; i < 9; i += 2)",
      "for (int i = 1; i == 9; i += 2)",
    ],
    points: 20,
    order: 5,
    answer: "for (int i = 1; i < 10; i += 2)",
  },
];

export const INITIAL_SETTINGS: AppSettings = {
  websiteName: "LOOPYU Classroom",
  schoolName: "SMP Bintang Edukasi",
  academicYear: "2026/2027",
  whoCanCreateTeams: "STUDENTS",
  maxTeamSize: 5,
  requireTeacherApproval: false,
  defaultPassingScore: 75,
  maxTestAttempts: 2,
};

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: "log-1",
    userId: "admin",
    userName: "Administrator",
    action: "SYSTEM_INITIALIZE",
    details: "Inisialisasi sistem database kelas LOOPYU dan struktur penugasan tim.",
    timestamp: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
  {
    id: "log-2",
    userId: "teacher01",
    userName: "Pak Hendra, S.Kom",
    action: "CREATE_ASSIGNMENT",
    details: "Menerbitkan penugasan 'Loop Challenge 01' untuk Kelas VIII A.",
    timestamp: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: "log-3",
    userId: "student01",
    userName: "Rizki",
    action: "CREATE_TEAM",
    details: "Membentuk tim baru 'LOOP MASTER' dengan kode 'LP-4821'.",
    timestamp: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
];
